language: objective-c
osx_image: xcode7.3
xcode_project: RMQClient.xcodeproj
xcode_scheme: RMQClient
xcode_sdk: iphonesimulator
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew install rabbitmq
  - brew services start rabbitmq
before_script:
  - carthage bootstrap --platform iOS
