language: objective-c
osx_image: xcode7.2
xcode_project: RMQClient.xcodeproj
xcode_scheme: RMQClientCI
xcode_sdk: iphonesimulator
before_install:
  - brew update
  - brew upgrade xctool
  - xctool -version
before_script:
  - carthage bootstrap
